name: Testing

on:
  workflow_call:

env:
  default-python: '3.13'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        tox_env: [py39, py310, py311, py312, py313]
        include:
          - tox_env: style
          - tox_env: docstyle
          - tox_env: coverage

    # The operative sistem
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    # the steps of the CI
    steps:
      - uses: actions/checkout@v4

      - name: Determine Python version
        id: pyversion
        if: ${{ startsWith(matrix.tox_env, 'py3') }}
        uses: bluwy/substitute-string-action@v1
        with:
          _input-text: ${{ matrix.tox_env }}
          _format-key: "py3=3."

      - name: Set up Python
        run: echo "PYTHON_VERSION=${{ steps.pyversion.outputs.result || env.default-python }}" >> $GITHUB_ENV

      - name: Use Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install tox
        run: pip install tox

      - name: tox -re ${{ matrix.tox_env }}
        run: tox -re ${{ matrix.tox_env }}
